//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.05 at 09:38:36 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/no0ker/MyExampleVer2Application", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.github_com.no0ker.myexamplever2application;
